import type { Property } from '@/components/catalog/types';

export const GERMANY_PROPERTIES: Property[] = [
  {
    id: 1,
    title: 'Mitte Panorama Penthouse',
    address: 'Friedrichstrasse 114, 10117 Berlin',
    city: 'Berlin',
    type: 'Penthouse',
    price: 2900,
    deposit: 8700,
    area: 115,
    rooms: 3,
    floor: '6th floor (attic level)',
    availableFrom: '01 Aug 2026',
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
    description:
      'Exclusive duplex penthouse in central Berlin with a private rooftop terrace, premium fitted kitchen, and skyline views.',
    furnished: true,
    petsAllowed: true,
    hasBalcony: true,
    hasParking: true,
    hasKitchen: true,
    amenities: ['Rooftop terrace', 'Direct lift access', 'Fireplace', 'Air conditioning', 'Built-in kitchen'],
  },
  {
    id: 2,
    title: 'Schwabing Premium Loft',
    address: 'Leopoldstrasse 42, 80802 Munich',
    city: 'Munich',
    type: 'Loft',
    price: 1850,
    deposit: 3700,
    area: 72,
    rooms: 2,
    floor: '3rd floor',
    availableFrom: '01 Jul 2026',
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
    description:
      'Industrial-style loft in Schwabing with exposed brick, large windows, and a high-end Bulthaup kitchen.',
    furnished: true,
    petsAllowed: false,
    hasBalcony: true,
    hasParking: true,
    hasKitchen: true,
    amenities: ['Balcony', 'Underground parking', 'Bulthaup kitchen', 'High ceilings'],
  },
  {
    id: 3,
    title: 'HafenCity Waterfront Apartment',
    address: 'Am Kaiserkai 12, 20457 Hamburg',
    city: 'Hamburg',
    type: 'Apartment',
    price: 2100,
    deposit: 6300,
    area: 88,
    rooms: 2.5,
    floor: '4th floor',
    availableFrom: '15 Jul 2026',
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
    description:
      'Modern waterfront apartment in HafenCity featuring floor heating, bright interiors, and premium city views.',
    furnished: false,
    petsAllowed: true,
    hasBalcony: true,
    hasParking: false,
    hasKitchen: true,
    amenities: ['Waterfront view', 'French balcony', 'Floor heating', 'Built-in kitchen'],
  },
  {
    id: 4,
    title: 'Westend Executive Studio',
    address: 'Bockenheimer Landstrasse 83, 60325 Frankfurt',
    city: 'Frankfurt',
    type: 'Studio',
    price: 1250,
    deposit: 2500,
    area: 45,
    rooms: 1,
    floor: '12th floor',
    availableFrom: 'Immediate',
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
    description:
      'Fully furnished minimalist studio in Frankfurt Westend, ideal for professionals looking for a central location.',
    furnished: true,
    petsAllowed: false,
    hasBalcony: false,
    hasParking: true,
    hasKitchen: true,
    amenities: ['Skyline view', 'Concierge', 'Air conditioning', 'Garage parking'],
  },
  {
    id: 5,
    title: 'Carlstadt Art-Villa Suite',
    address: 'Bastionstrasse 19, 40213 Dusseldorf',
    city: 'Dusseldorf',
    type: 'Villa',
    price: 3400,
    deposit: 10200,
    area: 145,
    rooms: 4,
    floor: 'Ground floor with garden access',
    availableFrom: '01 Sep 2026',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    description:
      'Luxury suite in a historic villa with private garden access, tall decorative ceilings, and top-tier finishes.',
    furnished: false,
    petsAllowed: true,
    hasBalcony: true,
    hasParking: true,
    hasKitchen: true,
    amenities: ['Private garden', 'High ceilings', 'Fireplace', 'Wine cellar', 'Private parking'],
  },
  {
    id: 6,
    title: 'Belgian Quarter Modern Flat',
    address: 'Brusseler Strasse 88, 50672 Cologne',
    city: 'Cologne',
    type: 'Apartment',
    price: 1550,
    deposit: 3100,
    area: 68,
    rooms: 2,
    floor: '2nd floor',
    availableFrom: '01 Aug 2026',
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
    description:
      'Contemporary two-room apartment in Cologne with a quiet balcony, oak parquet flooring, and energy-efficient standards.',
    furnished: true,
    petsAllowed: true,
    hasBalcony: true,
    hasParking: false,
    hasKitchen: true,
    amenities: ['Quiet balcony', 'Oak parquet', 'Built-in wardrobe', 'Energy efficient building'],
  },
];
