import type { AdminProfile, PaymentLedgerRow } from '@/components/admin/types';

export const REJECTION_PRESETS = [
  'Outdated Schufa statement (must be newer than 3 months)',
  'ID card image quality is too low to verify identity',
  'Selbstauskunft form is missing required signature fields',
  'Income proofs are missing for the latest 3 months',
  'Potential signs of document manipulation detected',
];

export const INITIAL_PROFILES: AdminProfile[] = [
  {
    id: 'usr_001',
    fullName: 'Oleksandr Kovalenko',
    email: 'o.kovalenko@gmail.com',
    registrationDate: '2026-06-10',
    role: 'CLIENT',
    status: 'Pending',
    rejectionReason: '',
    isBlocked: false,
    documents: {
      idCard: { name: 'ID_Kovalenko.pdf', size: '2.4 MB', uploadedAt: '2026-06-12', status: 'Uploaded' },
      schufa: {
        name: 'Schufa_Kovalenko_Q2.pdf',
        size: '1.1 MB',
        uploadedAt: '2026-06-12',
        status: 'Uploaded',
        score: '98.2%',
      },
      selbstauskunft: {
        name: 'Selbstauskunft_Signed.pdf',
        size: '850 KB',
        uploadedAt: '2026-06-12',
        status: 'Uploaded',
      },
    },
  },
  {
    id: 'usr_002',
    fullName: 'Mariia Petrenko',
    email: 'm.petrenko@yahoo.com',
    registrationDate: '2026-06-08',
    role: 'CLIENT',
    status: 'Pending',
    rejectionReason: '',
    isBlocked: false,
    documents: {
      idCard: { name: 'Passport_Petrenko.jpg', size: '4.1 MB', uploadedAt: '2026-06-14', status: 'Uploaded' },
      schufa: { name: 'Schufa_Petrenko.pdf', size: '920 KB', uploadedAt: '2026-06-14', status: 'Uploaded', score: '94.5%' },
      selbstauskunft: {
        name: 'Selbstauskunft_Mariia.pdf',
        size: '780 KB',
        uploadedAt: '2026-06-14',
        status: 'Uploaded',
      },
    },
  },
  {
    id: 'usr_003',
    fullName: 'Dmytro Lysenko',
    email: 'lysenkodm@outlook.com',
    registrationDate: '2026-05-20',
    role: 'CLIENT',
    status: 'Verified',
    rejectionReason: '',
    isBlocked: false,
    documents: {
      idCard: { name: 'ID_Lysenko_new.pdf', size: '1.8 MB', uploadedAt: '2026-05-21', status: 'Verified' },
      schufa: {
        name: 'Schufa_Lysenko_clean.pdf',
        size: '1.3 MB',
        uploadedAt: '2026-05-21',
        status: 'Verified',
        score: '99.1%',
      },
      selbstauskunft: { name: 'Selbst_Lysenko.pdf', size: '900 KB', uploadedAt: '2026-05-21', status: 'Verified' },
    },
  },
  {
    id: 'usr_004',
    fullName: 'Olena Moroz',
    email: 'moroz_olena@gmail.com',
    registrationDate: '2026-05-15',
    role: 'CLIENT',
    status: 'Verified',
    rejectionReason: '',
    isBlocked: false,
    documents: {
      idCard: { name: 'ID_Moroz.pdf', size: '2.2 MB', uploadedAt: '2026-05-16', status: 'Verified' },
      schufa: { name: 'Schufa_Moroz.pdf', size: '1.0 MB', uploadedAt: '2026-05-16', status: 'Verified', score: '97.8%' },
      selbstauskunft: { name: 'Selbstauskunft_Moroz.pdf', size: '820 KB', uploadedAt: '2026-05-16', status: 'Verified' },
    },
  },
  {
    id: 'usr_005',
    fullName: 'Andrii Shevchenko',
    email: 'sheva.rent@ukr.net',
    registrationDate: '2026-06-01',
    role: 'CLIENT',
    status: 'Rejected',
    rejectionReason: 'Uploaded Schufa report is outdated. Please upload a report issued within the last 3 months.',
    isBlocked: false,
    documents: {
      idCard: { name: 'ID_Shevchenko.jpg', size: '3.2 MB', uploadedAt: '2026-06-02', status: 'Rejected' },
      schufa: {
        name: 'Schufa_Shevchenko_2024.pdf',
        size: '1.5 MB',
        uploadedAt: '2026-06-02',
        status: 'Rejected',
        score: '89.0%',
      },
      selbstauskunft: { name: 'Selbstauskunft_Draft.pdf', size: '600 KB', uploadedAt: '2026-06-02', status: 'Rejected' },
    },
  },
  {
    id: 'agent_001',
    fullName: 'Mark Weber (Agent)',
    email: 'm.weber@flexxrent.com',
    registrationDate: '2026-01-10',
    role: 'AGENT',
    status: 'Verified',
    isBlocked: false,
    managedProperties: 4,
  },
  {
    id: 'agent_002',
    fullName: 'Christina Bauer (Agent)',
    email: 'c.bauer@flexxrent.com',
    registrationDate: '2026-03-05',
    role: 'AGENT',
    status: 'Verified',
    isBlocked: false,
    managedProperties: 7,
  },
  {
    id: 'agent_003',
    fullName: 'Thomas Schmidt (Agent)',
    email: 't.schmidt@flexxrent.com',
    registrationDate: '2026-04-12',
    role: 'AGENT',
    status: 'Verified',
    isBlocked: true,
    managedProperties: 2,
  },
];

export const INITIAL_PAYMENTS: PaymentLedgerRow[] = [
  {
    id: 'pay_101',
    clientName: 'Dmytro Lysenko',
    agentName: 'Mark Weber (Agent)',
    agentId: 'agent_001',
    propertyTitle: 'Apartment in Maxvorstadt, Munich',
    baseRent: 1200,
    utilityCosts: 250,
    deposit: 2400,
    totalPaid: 3850,
    paymentDate: '2026-06-02',
    status: 'PAID',
    payoutCalculated: false,
  },
  {
    id: 'pay_102',
    clientName: 'Olena Moroz',
    agentName: 'Christina Bauer (Agent)',
    agentId: 'agent_002',
    propertyTitle: 'Studio near English Garden, Munich',
    baseRent: 950,
    utilityCosts: 180,
    deposit: 1900,
    totalPaid: 3030,
    paymentDate: '2026-06-05',
    status: 'PAID',
    payoutCalculated: false,
  },
  {
    id: 'pay_103',
    clientName: 'Ihor Kravchenko',
    agentName: 'Christina Bauer (Agent)',
    agentId: 'agent_002',
    propertyTitle: 'Two-room apartment in Schwabing',
    baseRent: 1400,
    utilityCosts: 300,
    deposit: 2800,
    totalPaid: 4500,
    paymentDate: '2026-05-28',
    status: 'PAID',
    payoutCalculated: true,
  },
];
