import type { AgentBooking, AgentProperty } from '@/components/agent/types';

export const INITIAL_PROPERTIES: AgentProperty[] = [
  {
    id: 'prop_001',
    title: 'Maxvorstadt Apartment',
    address: 'Theresienstrasse 45, Munich',
    baseRent: 1200,
    utilityCosts: 250,
    rooms: 2,
    area: 55,
    status: 'Available',
    imagePlaceholder: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'prop_002',
    title: 'Studio Near English Garden',
    address: 'Koniginstrasse 12, Munich',
    baseRent: 950,
    utilityCosts: 180,
    rooms: 1,
    area: 38,
    status: 'Available',
    imagePlaceholder: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'prop_003',
    title: 'Two-Room Flat in Schwabing',
    address: 'Leopoldstrasse 88, Munich',
    baseRent: 1400,
    utilityCosts: 300,
    rooms: 2,
    area: 65,
    status: 'Rented',
    imagePlaceholder: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'prop_004',
    title: 'Industrial Loft in Glockenbachviertel',
    address: 'Mullerstrasse 31, Munich',
    baseRent: 1850,
    utilityCosts: 350,
    rooms: 3,
    area: 92,
    status: 'Available',
    imagePlaceholder: 'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?auto=format&fit=crop&w=800&q=80',
  },
];

export const INITIAL_BOOKINGS: AgentBooking[] = [
  {
    id: 'book_901',
    propertyId: 'prop_001',
    propertyName: 'Maxvorstadt Apartment',
    clientName: 'Oleksandr Kovalenko',
    clientEmail: 'o.kovalenko@gmail.com',
    clientStatus: 'Verified',
    requestedDate: '2026-06-22',
    status: 'Pending',
    timeLeft: null,
  },
  {
    id: 'book_902',
    propertyId: 'prop_002',
    propertyName: 'Studio Near English Garden',
    clientName: 'Mariia Petrenko',
    clientEmail: 'm.petrenko@yahoo.com',
    clientStatus: 'Verified',
    requestedDate: '2026-06-23',
    status: 'Pending',
    timeLeft: null,
  },
  {
    id: 'book_903',
    propertyId: 'prop_003',
    propertyName: 'Two-Room Flat in Schwabing',
    clientName: 'Dmytro Lysenko',
    clientEmail: 'lysenkodm@outlook.com',
    clientStatus: 'Verified',
    requestedDate: '2026-06-18',
    status: 'Paid',
    timeLeft: 0,
  },
];
